# Generated by Django 4.2 on 2023-05-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatnnovationApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
